<a href="https://colab.research.google.com/github/StefanOVFDE/Academypublic/blob/main/imhausen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#example

In [ ]:
!pip install -q kaggle
from google.colab import files
files.upload()
#create a kaggle folder
!mkdir ~/.kaggle
# Go on kaggle > Account > Create New API token
# Save the json file in your laptop in a dedicated folder
# copy the kaggle.json to folder created
!cp kaggle.json ~/.kaggle
#permission for the json to act
!chmod 600 ~/.kaggle/kaggle.json
# Datasets available here: 
# https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009
!kaggle datasets download -d uciml/red-wine-quality-cortez-et-al-2009
!unzip red-wine-quality-cortez-et-al-2009.zip

Saving kaggle.json to kaggle.json
Downloading red-wine-quality-cortez-et-al-2009.zip to /content
  0% 0.00/25.6k [00:00<?, ?B/s]
100% 25.6k/25.6k [00:00<00:00, 9.71MB/s]
Archive:  red-wine-quality-cortez-et-al-2009.zip
  inflating: winequality-red.csv

In [ ]:
# Data types
# Most used: list

cities = ['Paris','Zurich','Milan','Berlin','Londn']

new_list = [1,2,3,4]

valueToBeRemoved = "4"
cities=[element for element in cities if element !=valueToBeRemoved]

val = 1
if val > 0:
  print('the value is positive')
elif val <0:
  print('the value is negaitve')
else:
  print('the value equals 0')

In [ ]:

fruits = ['apple', 'pear','cherry', 'nuts']
for stefan in fruits:
  print(stefan)

apple
pear
cherry
nuts

In [ ]:
def multiply(a,b):
  calc = a * b
  return calc

multiply(10,5)

50

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/winequality-red.csv')

In [ ]:
df[['fixed acidity','volatile acidity','chlorides','pH']].head(5)

   fixed acidity  volatile acidity  chlorides    pH
0            7.4              0.70      0.076  3.51
1            7.8              0.88      0.098  3.20
2            7.8              0.76      0.092  3.26
3           11.2              0.28      0.075  3.16
4            7.4              0.70      0.076  3.51

In [ ]:
mask1 = df['fixed acidity']>7
df[mask1]

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4              0.70         0.00  ...       0.56      9.4        5
1               7.8              0.88         0.00  ...       0.68      9.8        5
2               7.8              0.76         0.04  ...       0.65      9.8        5
3              11.2              0.28         0.56  ...       0.58      9.8        6
4               7.4              0.70         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1576            8.0              0.30         0.63  ...       0.78     10.8        6
1580            7.4              0.35         0.33  ...       0.60     11.9        6
1585            7.2              0.39         0.44  ...       0.84     11.5        6
1586            7.5              0.31         0.41  ...       0.85     11.4        6
1588            7.2              0.66         0.33  ...       0.78     12.8        6

[1237 rows x 12 columns]

In [ ]:
def citric_acid_cat(x):
  if x < 0.21 :
    return 'A'
  elif x < 0.3 :
    return 'B'
  else:
    return 'C'

In [ ]:
df['citric_cat'] = df['citric acid'].apply(lambda x: citric_acid_cat(x))

In [ ]:
df.head(20)

    fixed acidity  volatile acidity  citric acid  ...  alcohol  quality  citric_cat
0             7.4             0.700         0.00  ...      9.4        5           A
1             7.8             0.880         0.00  ...      9.8        5           A
2             7.8             0.760         0.04  ...      9.8        5           A
3            11.2             0.280         0.56  ...      9.8        6           C
4             7.4             0.700         0.00  ...      9.4        5           A
5             7.4             0.660         0.00  ...      9.4        5           A
6             7.9             0.600         0.06  ...      9.4        5           A
7             7.3             0.650         0.00  ...     10.0        7           A
8             7.8             0.580         0.02  ...      9.5        7           A
9             7.5             0.500         0.36  ...     10.5        5           C
10            6.7             0.580         0.08  ...      9.2        5           A
11            7.5             0.500         0.36  ...     10.5        5           C
12            5.6             0.615         0.00  ...      9.9        5           A
13            7.8             0.610         0.29  ...      9.1        5           B
14            8.9             0.620         0.18  ...      9.2        5           A
15            8.9             0.620         0.19  ...      9.2        5           A
16            8.5             0.280         0.56  ...     10.5        7           C
17            8.1             0.560         0.28  ...      9.3        5           B
18            7.4             0.590         0.08  ...      9.0        4           A
19            7.9             0.320         0.51  ...      9.2        6           C

[20 rows x 13 columns]